# Generated by Django 5.1.1 on 2024-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="Имя автора"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Фамилия автора"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="BookIssuance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата выдачи"),
                ),
                ("due_date", models.DateField(verbose_name="Дата возврата")),
                (
                    "returned",
                    models.BooleanField(default=False, verbose_name="Возвращена"),
                ),
            ],
            options={
                "verbose_name": "Выдача книги",
                "verbose_name_plural": "Выдачи книг",
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название книги"),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год издания"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Жанр"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
