# Generated by Django 5.1.1 on 2024-09-22 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookissuance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="books",
            name="author",
            field=models.ManyToManyField(
                max_length=255, to="books.author", verbose_name="Автор"
            ),
        ),
        migrations.AddField(
            model_name="bookissuance",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.books",
                verbose_name="Выданная книга",
            ),
        ),
    ]
