# Generated by Django 5.1.1 on 2024-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="author",
            field=models.ManyToManyField(
                max_length=255,
                related_name="author_book",
                to="books.author",
                verbose_name="Автор",
            ),
        ),
    ]
